// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVggzmoG7Ywh5jiT-ncXXHb0czm-3VGg',
    appId: '1:284920895387:web:810578bb86bdc564ed333e',
    messagingSenderId: '284920895387',
    projectId: 'databank-6f630',
    authDomain: 'databank-6f630.firebaseapp.com',
    storageBucket: 'databank-6f630.appspot.com',
    measurementId: 'G-57GWT5W0QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3Lqn3KgPepRArhcbvAnw8Lkr0CJ84YA',
    appId: '1:284920895387:android:06e3f957a47046cfed333e',
    messagingSenderId: '284920895387',
    projectId: 'databank-6f630',
    storageBucket: 'databank-6f630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2lboPRP06SOjBM0_lOJJUBINoAE25SQ',
    appId: '1:284920895387:ios:52ef4adbe2bf38baed333e',
    messagingSenderId: '284920895387',
    projectId: 'databank-6f630',
    storageBucket: 'databank-6f630.appspot.com',
    iosBundleId: 'com.daniel.databank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2lboPRP06SOjBM0_lOJJUBINoAE25SQ',
    appId: '1:284920895387:ios:d6e0c7971b8108ffed333e',
    messagingSenderId: '284920895387',
    projectId: 'databank-6f630',
    storageBucket: 'databank-6f630.appspot.com',
    iosBundleId: 'com.daniel.databank.RunnerTests',
  );
}
